const Section= {
    SHIFT_SALE : 'Shift-Sale',
    POS : 'Pos',
    POS_HISTORY : 'Pos-History',
    COMPANY_SALE : 'Company-Sale',
    TANK_REFILL : 'Tank-Refill',
    TANK_VISUAL : 'Tank-Visual',
    TANK_READING : 'Tank-Reading',
    NOZZLE_READING : 'Nozzle-Reading',
    PAY_ORDER : 'Pay-Order',
    TRANSFER : 'Transfer',
    EXPENSE : 'Expense',
    BILL : 'Bill',
    EMPLOYEE : 'Employee',
    SALARY : 'Salary',
    ATTENDANCE : 'Attendance',
    TANK : 'Tank',
    DISPENSER : 'Dispenser',
    NOZZLE : 'Nozzle',
    PRODUCT : 'Product',
    BANK : 'Bank',
    VENDOR : 'Vendor',
    CREDIT_COMPANY : 'Credit-Company',
    USER : 'User',
    SYSTEM_SETTING : 'System-Setting',
    VOUCHER : 'Voucher',
    DRIVER : 'Driver',
    ACCOUNTING : 'Accounting',
    DAILY_REPORT : 'Daily-Report',
    BALANCE_SHEET : 'Balance-Sheet',
    PROFIT_AND_LOSS : 'Profit-and-Loss',
    INCOME_STATEMENT : 'Income-Statement',
    ACCOUNT_PAYABLE : 'Account-Payable',
    ACCOUNT_RECEIVABLE : 'Account-Receivable',
    TRAIL_BALANCE : 'Trail-Balance',
    LEDGER : 'Ledger',
    ROLE : 'Role',
    POS_MACHINE: 'Pos-Machine',
    INVOICE: 'Invoice',
    FUEL_ADJUSTMENT: 'Fue-Adjustment',
    UNAUTHORIZED_BILL: 'Unauthorized-Bill',
    SALES_REPORT: 'Sales-Report',
    COMPANY_BILL: 'Company-Bill'
}
export default Section;

